### ISSUE TITLE
Exception: Library could not be loaded!

### ISSUE THREAD

**Issue by eternalsystem** [jonasroussel/system_resources#5]
I have this on debian x86_64 : Unhandled exception:
Exception: Library could not be loaded!
#0      loadLibsysres.<anonymous closure> (package:system_resources/src/dylib.dart:47)
<asynchronous suspension>
#1      SystemResources.init (package:system_resources/src/base.dart:11)
<asynchronous suspension>

**Comment by fstof** [comment]
Also getting the same
Running dart app
But it only happens when I run dart app compiled to exe with `dart compile exe bin/main.dart -o bin/main`
Running with dart cli works fine

```
Unhandled exception:
Exception: Library could not be loaded!
#0      loadLibsysres.<anonymous closure> (package:system_resources/src/dylib.dart:47)
<asynchronous suspension>
#1      SystemResources.init (package:system_resources/src/base.dart:11)
```
